### ISSUE TITLE
Handler extensions don't respect stashed checks

### ISSUE THREAD

**Issue by gffhcks** [sensu/sensu-extension#2]
I'm using the Flapjack Handler extension from sensu-community-plugins. When I implemented it, I expected the extension to work like regular plugin extensions do - if you apply a Stash to a check, it ignores that check until the stash expires.  But from what I can tell, extensions ignore stashes completely.

I could modify the extension to check stashes in the same way that the sensu-plugin code does. But that approach requires you to duplicate the code for every handler extension that you want to actually respect stashes. Would there be any way to implement this directly in extensions instead, possibly with a config toggle allowing it to be turned on or off?

**Comment by cwjohnston** [comment]
@gffhcks thanks for opening this issue, now almost two years ago! 

We've recently released Sensu 0.26 with built-in silencing, described [here in our reference doc](https://sensuapp.org/docs/0.26/reference/silencing.html). This silencing implementation works with extensions as well as plugins, making silencing a real first-class citizen.
